---

# determines whether the dashboard is enabled
enable_dashboard: yes

# Which TCP port will the dashboard listen on
listen_port: 8888

# hide_log is useful if the dashboard will be published publicly. He turns off the log channel,
# and hides most of the details associated with the node. Please be aware that this is not fully tested to prevent
# information leaks about node names, etc.
hide_logs: no

# How long should you wait before notifying that a node is down?
node_down_alert_minutes: 3

# Should the prometheus exporter be enabled?
prometheus_enabled: yes
# What port should it listen on?
prometheus_listen_port: 20360
prometheus_listen_port: 20100
prometheus_listen_port: 26660

# Global setting
pagerduty:
  # Should we use PD? Please note that if this setting is set to no, it will override the individual chain alert settings.
  enabled: no
  # This is an API key, not an oauth token, more details below, but check out the v1 docs for more information.
  api_key: aaaaaaaaaaaabbbbbbbbbbbbbcccccccccccc
  # Currently not in use, but will be used soon. This allows you to set escalation priorities, etc.
  default_severity: alert

# Discord Settings
discord:
  # Alerts on discord?
  enabled: yes
  # The webhook is configured by right-clicking on the channel, editing the settings and configuring the webhook in the integration section.
  webhook: https://discord.com/api/webhooks/10134860xxxxxxxx......xxxxxxxNdu4QmfojbyC-Uozbtz2bzBp.............x2

# Telegram settings
telegram:
  # Telegram alert? Note: Also replaces network-specific settings
  enabled: no
  # API key... talk to @BotFather
  api_key: '5555555555:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  # ID of the chat group to which messages will be sent
  channel: "-666666666"

# Various chains to be monitored. Create a new entry for each network
chains:

  # A user-friendly name that will be used for the labels. I strongly recommend putting it in quotes

################################################################################
# Then you can add the second and subsequent networks... Uncomment and change  #
################################################################################
chains:
  "Lava-T":
    chain_id: lava-testnet-2
    valoper_address: lava@valoper1pwrwgqe8lk06c6y0md2cnwznlutzlv867kt4mc
    public_fallback: yes

    alerts:
      stalled_enabled: yes
      stalled_minutes: 10
      consecutive_enabled: yes
      consecutive_missed: 5
      consecutive_priority: critical
      percentage_enabled: no
      percentage_missed: 10
      percentage_priority: warning
      alert_if_inactive: yes
      alert_if_no_servers: yes

      pagerduty:
        enabled: yes
        api_key: "" # default if empty

      discord:
        enabled: yes
        webhook: https://discord.com/api/webhooks/10134860xxxxxxxx......xxxxxxxNdu4QmfojbyC-Uozbtz2bzBp.............x2

      telegram:
        enabled: yes
        api_key: "" # default if empty
        channel: "" # default if empty

    nodes:
      - url: http://65.21.224.11:26757
        alert_if_down: no
      - url: http://161.97.71.152:26657
        alert_if_down: no

################################################################################
chains:
  "Dymension-M":
    chain_id: dymension_1100-1
    valoper_address: dymvaloper20mxp0k0hg4e0rxg05v07t9ka2tfuhamhldgf8e
    public_fallback: yes

    alerts:
      stalled_enabled: yes
      stalled_minutes: 10
      consecutive_enabled: yes
      consecutive_missed: 5
      consecutive_priority: critical
      percentage_enabled: no
      percentage_missed: 10
      percentage_priority: warning
      alert_if_inactive: yes
      alert_if_no_servers: yes

      pagerduty:
        enabled: yes
        api_key: "" # default if empty

      discord:
        enabled: yes
        webhook: https://discord.com/api/webhooks/10134860xxxxxxxx......xxxxxxxNdu4QmfojbyC-Uozbtz2bzBp.............x2

      telegram:
        enabled: yes
        api_key: "" # default if empty
        channel: "" # default if empty

    nodes:
      - url: https://dym.rpc.m.stavr.tech:443
        alert_if_down: no
      - url: http://107.182.163.2:31891
        alert_if_down: no

################################################################################
