#!/bin/bash
MAGNETA=$(tput setaf 5)
RESET=$(tput sgr0)

while true
do

# Logo

curl -s https://raw.githubusercontent.com/111STAVR111/props/main/logo_1.txt | bash

# Menu

PS3='Select an action: '
options=(
"Install Node"
"Check logs"
"Sync status"
"Check sync info"
"Check validator info"
"Create wallet"
"Check Version"
"Synchronization via Statesync"
"Synchronization via SnapShot (Pruned)"
"UPDATE"
"Delete Node"
"Exit")
select opt in "${options[@]}"
do
case $opt in

"Install Node")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read Validator_Name
echo "_|-_|-_|-_|-_|-_|-_|"
echo export Validator_Name=${Validator_Name} >> $HOME/.bash_profile
echo export CHAIN_ID="arkeo-main-v1" >> $HOME/.bash_profile
source ~/.bash_profile
echo -e "\e[1m\e[32m	DO YOU WANT TO CHANGE THE DEFAULT PORTS? (yes/no):\e[0m"
read change_ports
change_ports=$(echo "$change_ports" | tr '[:upper:]' '[:lower:]')
if [[ "$change_ports" == "yes" || "$change_ports" == "y" ]]; then
    echo -e "\e[1m\e[32m	Enter the new first two digits for the proxy_app port (26658):\e[0m"
    read proxy_app_prefix
    echo -e "\e[1m\e[32m	Enter the new first two digits for the rpc port (26657):\e[0m"
    read rpc_prefix
    echo -e "\e[1m\e[32m	Enter the new first two digits for the p2p port (26656):\e[0m"
    read p2p_prefix
    echo -e "\e[1m\e[32m	Enter the new first two digits for the pprof port (6060):\e[0m"
    read pprof_prefix
    echo -e "\e[1m\e[32m	Enter the new first two digits for the grpc port (9090):\e[0m"
    read grpc_prefix
    echo -e "\e[1m\e[32m	Enter the new first two digits for the grpc-web port (9091):\e[0m"
    read grpc_web_prefix
    if ! [[ "$proxy_app_prefix" =~ ^[0-9]{2}$ ]] || ! [[ "$rpc_prefix" =~ ^[0-9]{2}$ ]] || ! [[ "$p2p_prefix" =~ ^[0-9]{2}$ ]]; then
        echo "Invalid input. Ports will not be changed."
        change_ports="n"
    fi
fi

echo -e "\e[1m\e[32m1. Updating packages and dependencies--> \e[0m" && sleep 1
# UPDATE APT
sudo apt update && sudo apt upgrade -y
sudo apt install curl tar wget clang pkg-config libssl-dev libleveldb-dev jq build-essential bsdmainutils git make ncdu htop screen unzip bc fail2ban htop -y
echo "${MAGNETA}🔥Dependencies updated 🔥${RESET}"
sleep 1

echo -e "        \e[1m\e[32m2. Installing GO--> \e[0m" && sleep 1
# INSTALL GO
ver="1.21.6"
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> $HOME/.bash_profile
source $HOME/.bash_profile
go version
echo "${MAGNETA}🔥GO is installed 🔥${RESET}"
sleep 1

echo -e "              \e[1m\e[32m3. Downloading and building binaries--> \e[0m" && sleep 1
# INSTALL
cd $HOME && mkdir $HOME/go/bin/
git clone https://github.com/arkeonetwork/arkeo
cd arkeo
git checkout v1.0.9
make install
echo "${MAGNETA}🔥Binaries installed successfully 🔥${RESET}"
sleep 1
arkeod init $Validator_Name --chain-id $CHAIN_ID

if [ "$change_ports" == "y" ]; then
    echo "Changing proxy_app port..."
    sed -i "s/tcp:\/\/127\.0\.0\.1:26658/tcp:\/\/127.0.0.1:${proxy_app_prefix}658/" $HOME/.arkeo/config/config.toml
    echo "Changing rpc port..."
    sed -i "s/tcp:\/\/127\.0\.0\.1:26657/tcp:\/\/127.0.0.1:${rpc_prefix}657/" $HOME/.arkeo/config/config.toml
    echo "Changing p2p port..."
    sed -i "s/tcp:\/\/0\.0\.0\.0:26656/tcp:\/\/0.0.0.0:${p2p_prefix}656/" $HOME/.arkeo/config/config.toml
    echo "Changing pprof port..."
    sed -i "s/pprof_laddr = \"localhost:6060\"/pprof_laddr = \"localhost:${pprof_prefix}60\"/" $HOME/.arkeo/config/config.toml
    echo "Changing grpc port..."
    sed -i "s/address = \"localhost:9090\"/address = \"localhost:${grpc_prefix}90\"/" $HOME/.arkeo/config/app.toml
    echo "Changing grpc-web port..."
    sed -i "s/address = \"localhost:9091\"/address = \"localhost:${grpc_web_prefix}91\"/" $HOME/.arkeo/config/app.toml
    echo "Ports have been updated to ${proxy_app_prefix}658, ${rpc_prefix}657, ${p2p_prefix}656, ${pprof_prefix}60, ${grpc_prefix}90 and ${grpc_web_prefix}91."
fi


wget -O $HOME/.arkeo/config/genesis.json "https://server-1.stavr.tech/Mainnet/Arkeo/genesis.json"
wget -O $HOME/.arkeo/config/addrbook.json "https://server-1.stavr.tech/Mainnet/Arkeo/addrbook.json"
sed -i.bak -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.001uarkeo\"/;" ~/.arkeo/config/app.toml
external_address=$(wget -qO- eth0.me) 
sed -i.bak -e "s/^external_address *=.*/external_address = \"$external_address:26656\"/" $HOME/.arkeo/config/config.toml
peers=""
sed -i.bak -e "s/^persistent_peers *=.*/persistent_peers = \"$peers\"/" $HOME/.arkeo/config/config.toml
seeds=""
sed -i.bak -e "s/^seeds =.*/seeds = \"$seeds\"/" $HOME/.arkeo/config/config.toml
sed -i 's/max_num_inbound_peers =.*/max_num_inbound_peers = 50/g' $HOME/.arkeo/config/config.toml
sed -i 's/max_num_outbound_peers =.*/max_num_outbound_peers = 50/g' $HOME/.arkeo/config/config.toml

pruning="custom"
pruning_keep_recent="1000"
pruning_keep_every="0"
pruning_interval="10"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/.arkeo/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/.arkeo/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/.arkeo/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/.arkeo/config/app.toml
echo "${MAGNETA}🔥Ports and peers updated 🔥${RESET}"
sleep 1
# Setup systemd services
tee /etc/systemd/system/arkeod.service > /dev/null <<EOF
[Unit]
Description=arkeod
After=network-online.target

[Service]
User=$USER
ExecStart=$(which arkeod) start
Restart=on-failure
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

# Start and enable services
sudo systemctl daemon-reload
sudo systemctl enable arkeod
sudo systemctl restart arkeod
echo "${MAGNETA}🔥Service files are installed and running 🔥${RESET}"

echo '=============== SETUP FINISHED ==================='
echo -e 'Congratulations:        \e[1m\e[32mSUCCESSFUL NODE INSTALLATION\e[0m'
echo -e 'To check logs:        \e[1m\e[33mjournalctl -fu arkeod -ocat\e[0m'
echo -e "To check sync status: \e[1m\e[35mcurl -s http://localhost:${rpc_prefix}657/status | jq .result.sync_info\e[0m"

break
;;
"Create wallet")
echo "_|-_|-_|-_|-_|-_|-_|"
echo -e "      \e[1m\e[35m Your WalletName:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read Wallet
echo export Wallet=${Wallet} >> $HOME/.bash_profile
source ~/.bash_profile
arkeod keys add $Wallet
echo -e "      \e[1m\e[32m!!!!!!!!!SAVE!!!!!!!!!!!!!!!!SAVE YOUR MNEMONIC PHRASE!!!!!!!!!SAVE!!!!!!!!!!!!!!!!\e[0m'"

break
;;
"UPDATE")
echo -e "      \e[1m\e[32m SOOOON\e[0m"
arkeod version

break
;;
"Check logs")
sudo journalctl -fu arkeod -n100 -ocat

break
;;
"Synchronization via Statesync")
echo -e "      \e[1m\e[32m SOOOON\e[0m"


break
;;
"Synchronization via SnapShot (Pruned)")
echo -e "      \e[1m\e[32m SOOOON\e[0m"


break
;;
"Check validator info")
curl localhost:$(sed -n '/\[rpc\]/,/laddr/ { /laddr/ {s/.*://; s/".*//; p} }' $HOME/.arkeo/config/config.toml)/status | jq

break
;;
"Check Version")
version_output=$(arkeod version --long | grep -e version -e commit 2>&1)
echo -e "\e[32m${version_output}\e[0m"

break
;;
"Check sync info")
RPC_PORT=$(sed -n '/\[rpc\]/,/laddr/ { /laddr/ {s/.*://; s/".*//; p} }' $HOME/.arkeo/config/config.toml)
curl -s http://localhost:$RPC_PORT/status | jq .result.sync_info

break
;;
"Sync status")
RPC_PORT=$(grep '^laddr' $HOME/.arkeo/config/config.toml | head -n 1 | awk -F':' '{print $NF}' | tr -d '"')
while true; do
    local_height=$(curl -s localhost:$RPC_PORT/status | jq -r '.result.sync_info.latest_block_height')
    network_height=$(curl -s https://arkeo.rpc.m.stavr.tech/status | jq -r '.result.sync_info.latest_block_height')
    blocks_left=$((network_height - local_height))
    
    estimated_time=$(echo "$blocks_left * 1.60" | bc)
    
    hours=$(echo "$estimated_time / 3600" | bc)
    minutes=$(echo "($estimated_time % 3600) / 60" | bc)

    echo -e "\033[1;38mYour height:\033[0m \033[1;32m$local_height\033[0m | \033[1;35mNetwork height:\033[0m \033[1;36m$network_height\033[0m | \033[1;29mBlocks left:\033[0m \033[1;31m$blocks_left\033[0m | \033[1;33mEstimated time: $hours hours $minutes minutes\033[0m"
    sleep 5
done

break
;;
"Delete Node")
echo -e "\e[31mAre you sure you want to delete the node? (Yes/No):\e[0m"
read confirmation

if [ "$confirmation" == "Yes" ]; then
    echo -e "\e[32m$confirmation\e[0m - Starting deletion process."

sudo systemctl stop arkeod
sudo systemctl disable arkeod
rm /etc/systemd/system/arkeod.service
sudo systemctl daemon-reload
cd $HOME
rm -rf arkeo
rm -rf .arkeo
rm -rf $(which arkeod)

    echo "Node has been successfully deleted."
else
    echo "Node deletion cancelled."
fi

break
;;
"Exit")
exit
esac
done
done
