#!/bin/bash
MAGNETA=$(tput setaf 5)
RESET=$(tput sgr0)

while true
do

# Logo

curl -s https://raw.githubusercontent.com/111STAVR111/props/main/logo_1.txt | bash

# Menu

PS3='Select an action: '
options=(
"Install Node"
"Check wallet"
"Check node logs"
"Check node status"
"Synchronization via SnapShot (Archive)"
"UPDATE"
"Delete Node"
"Exit")
select opt in "${options[@]}"
do
case $opt in

"Install Node")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
read -p "Enter your IP address RPC Node: " IP
read -p "Enter your RPC Port from your RPC Node: " RPC_PORT
read -p "Enter your gRPC Port from your RPC Node: " gRPC_PORT
read -p "Enter your Wallet name: " Wallet


echo -e "\e[1m\e[32m1. Updating packages and dependencies--> \e[0m" && sleep 1
#UPDATE APT
sudo apt update && sudo apt upgrade -y
sudo apt install curl tar wget clang pkg-config libssl-dev libleveldb-dev jq build-essential bsdmainutils git make ncdu htop screen unzip bc fail2ban htop -y
echo "${MAGNETA}🔥Dependencies updated 🔥${RESET}"
sleep 1

echo -e "        \e[1m\e[32m2. Installing GO--> \e[0m" && sleep 1
#INSTALL GO
ver="1.23.1"
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> $HOME/.bash_profile
source $HOME/.bash_profile
go version
echo "${MAGNETA}🔥GO is installed 🔥${RESET}"
sleep 1

echo -e "              \e[1m\e[32m3. Downloading and building binaries--> \e[0m" && sleep 1
#INSTALL
cd $HOME && mkdir -p go/bin/
git clone https://github.com/celestiaorg/celestia-node.git
cd celestia-node/
git checkout tags/v0.21.3-mocha
make build 
sudo make install 
make cel-key
mv $HOME/celestia-node/cel-key /usr/local/bin/

#Set up variables
echo "export IP=\"$IP\"" >> ~/.bash_profile
echo 'export RPC_PORT="$RPC_PORT"' >> ~/.bash_profile
echo 'export gRPC_PORT="$gRPC_PORT"' >> ~/.bash_profile
echo 'export Wallet="$Wallet"' >> ~/.bash_profile
source ~/.bash_profile

cel-key add $Wallet --keyring-backend test --node.type light --p2p.network mocha
echo -e "      \e[1m\e[32m!!!!!!!!!SAVE!!!!!!!!!!!!!!!!SAVE YOUR MNEMONIC PHRASE!!!!!!!!!SAVE!!!!!!!!!!!!!!!!\e[0m'"

celestia light init --p2p.network mocha

sudo tee /etc/systemd/system/celestia-light.service > /dev/null <<EOF
[Unit]
Description=celestia light
After=network-online.target

[Service]
User=$USER
ExecStart=$(which celestia) light start \
--core.ip $IP \
--core.rpc.port $RPC_PORT \
--core.grpc.port $gRPC_PORT \
--keyring.keyname $Wallet \
--p2p.network mocha \
--metrics.tls=true \
--metrics --metrics.endpoint otel.mocha.celestia.observer
Restart=on-failure
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF


# start service
sudo systemctl daemon-reload
sudo systemctl enable celestia-light
sudo systemctl restart celestia-light
echo "${MAGNETA}🔥Service files are installed and running 🔥${RESET}"

echo '=============== SETUP FINISHED ==================='
echo -e 'Congratulations:        \e[1m\e[32mSUCCESSFUL NODE INSTALLATION\e[0m'
echo -e 'To check logs:        \e[1m\e[33mjournalctl -fu celestia-light -ocat\e[0m'
echo -e "To check sync status: \e[1m\e[35mcelestia header sync-state --node.store  ~/.celestia-light-mocha-4\e[0m"


break
;;
"Check wallet")
cel-key list --node.type light --keyring-backend test --p2p.network mocha

break
;;
"UPDATE")
cd $HOME/celestia-node/
git pull
git checkout tags/v0.21.3-mocha
make build 
make install 
make cel-key
sudo systemctl restart celestia-light && sudo journalctl -fu celestia-light -ocat

break
;;
"Check node logs")
sudo journalctl -fu celestia-light -o cat

break
;;
"Check node status")
celestia header sync-state --node.store ~/.celestia-light-mocha-4/

break
;;
"Synchronization via SnapShot (Archive)")
cd $HOME
YELLOW='\033[1;33m'
GREEN='\033[1;32m'
PINK='\033[1;35m'
BLUE='\033[1;34m'
NO_COLOR='\033[0m'
SNAPSHOT_INFO_URL="https://light-data-t.stavr.tech/snapshot-info"
SNAPSHOT_INFO=$(curl -s $SNAPSHOT_INFO_URL)
BLOCK_HEIGHT=$(echo $SNAPSHOT_INFO | jq -r '.block_height')
CREATION_TIME=$(echo $SNAPSHOT_INFO | jq -r '.creation_time')
FILE_SIZE=$(echo $SNAPSHOT_INFO | jq -r '.file_size')
echo -e "Block Height: ${YELLOW}$BLOCK_HEIGHT${NO_COLOR}"
echo -e "Creation Time: ${GREEN}$CREATION_TIME${NO_COLOR}"
echo -e "File Size (Archive): ${BLUE}$FILE_SIZE${NO_COLOR}"
read -p "Do you want to continue with synchronization via Archive snapshot? (yes/no): " USER_CHOICE
USER_CHOICE=$(echo "$USER_CHOICE" | tr '[:upper:]' '[:lower:]')
if [[ "$USER_CHOICE" == "yes" || "$USER_CHOICE" == "y" ]]; then
    echo "Proceeding with synchronization..."
    snap list | grep -q lz4 || snap install lz4
	cd $HOME
	sudo systemctl stop celestia-light
	rm -rf $HOME/.celestia-light-mocha-4/data
	curl -o - -L https://celestia.light-archive.snap-t.stavr.tech/light-t-snap.tar.lz4 | lz4 -c -d - | tar -x -C $HOME/.celestia-light-mocha-4/
	sudo systemctl restart celestia-light && sudo journalctl -fu celestia-light -ocat
else
    echo "Operation cancelled. Returning to menu..."
fi


break
;;
"Delete Node")
echo -e "\e[31mAre you sure you want to delete the node? (Yes/No):\e[0m"
read confirmation

if [ "$confirmation" == "Yes" ]; then
	echo -e "\e[32m$confirmation\e[0m - Starting deletion process."

systemctl stop celestia-light
systemctl disable celestia-light
rm /etc/systemd/system/celestia-light.service
systemctl daemon-reload
cd $HOME
rm -rf .celestia-light-mocha-4
rm -rf .celestia-app
rm -rf celestia-node
rm -rf /usr/local/bin/cel-key
rm -rf $(which celestia)

    echo "Node has been successfully deleted."
else
    echo "Node deletion cancelled."
fi

break
;;
"Exit")
exit
esac
done
done
